name: Build

on:
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            localhost:5000/pgtest:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Start PGTest Image
        run: docker run localhost:5000/pgtest:latest
